version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/spacex-api
    volumes:
      - .:/usr/src/spacex-api
    ports:
      - '5000:5000'
    links:
      - mongo
    depends_on:
      - mongo
